# generated by ModelBuilder
from functools import cached_property
from scielo_classic_website.isisdb.meta_record import MetaRecord

ATTRIBUTES = (
    "journal",
    "start_month",
    "end_month",
    "is_ahead_of_print",
    "url",
    "assets_code",
    "label",
    "type",
    "volume",
    "number",
    "titles",
    "order",
    "is_press_release",
    "bibliographic_legends",
    "bibliographic_strip",
    "sections",
    "publication_date",
    "controlled_vocabulary",
    "processing_date",
    "update_date",
    "creation_date",
    "editorial_standard",
    "total_documents",
    "supplement_volume",
    "supplement_number",
    "is_marked_up",
    "permissions",
    "scielo_domain",
    "publisher_id",
    "collection_acronym",
)


def adapt_data(original):
    data = {}
    data["journal"] = original["journal"]
    data["start_month"] = original["start_month"]
    data["end_month"] = original["end_month"]
    data["is_ahead_of_print"] = original["is_ahead_of_print"]
    data["url"] = original["url"]
    data["assets_code"] = original["assets_code"]
    data["label"] = original["label"]
    data["type"] = original["type"]
    data["volume"] = original["volume"]
    data["number"] = original["number"]
    data["titles"] = original["titles"]
    data["order"] = original["order"]
    data["is_press_release"] = original["is_press_release"]
    data["bibliographic_legends"] = original["bibliographic_legends"]
    data["bibliographic_strip"] = original["bibliographic_strip"]
    data["sections"] = original["sections"]
    data["publication_date"] = original["publication_date"]
    data["controlled_vocabulary"] = original["controlled_vocabulary"]
    data["processing_date"] = original["processing_date"]
    data["update_date"] = original["update_date"]
    data["creation_date"] = original["creation_date"]
    data["editorial_standard"] = original["editorial_standard"]
    data["total_documents"] = original["total_documents"]
    data["supplement_volume"] = original["supplement_volume"]
    data["supplement_number"] = original["supplement_number"]
    data["is_marked_up"] = original["is_marked_up"]
    data["permissions"] = original["permissions"]
    data["scielo_domain"] = original["scielo_domain"]
    data["publisher_id"] = original["publisher_id"]
    data["collection_acronym"] = original["collection_acronym"]
    return data


# generated by ModelBuilder
class BaseIssueRecord(MetaRecord):
    def __init__(self, record, multi_val_tags=None, data_dictionary=None):
        super().__init__(record, multi_val_tags, data_dictionary)

    # generated by ModelBuilder
    @cached_property
    def attributes(self):
        return dict([(k, getattr(self, k)) for k in ATTRIBUTES])

    # generated by ModelBuilder
    @cached_property
    def journal(self):
        """
        Journal
        v035
        """
        return self.get_field_content("v035", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def start_month(self):
        """
        Start Month
        v000
        """
        return self.get_field_content("v000", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def end_month(self):
        """
        End Month
        v000
        """
        return self.get_field_content("v000", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def is_ahead_of_print(self):
        """
        Is Ahead Of Print
        v000
        """
        return self.get_field_content("v000", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def url(self):
        """
        Url
        v000
        """
        return self.get_field_content("v000", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def assets_code(self):
        """
        Assets Code
        v004
        """
        return self.get_field_content("v004", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def label(self):
        """
        Label
        v004
        """
        return self.get_field_content("v004", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def type(self):
        """
        Type
        v031
        """
        return self.get_field_content("v031", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def volume(self):
        """
        Volume
        v031
        """
        return self.get_field_content("v031", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def number(self):
        """
        Number
        v032
        """
        return self.get_field_content("v032", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def titles(self):
        """
        Titles
        v033
        """
        return self.get_field_content("v033", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def order(self):
        """
        Order
        v036
        """
        return self.get_field_content("v036", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def is_press_release(self):
        """
        Is Press Release
        v041
        """
        return self.get_field_content("v041", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def bibliographic_legends(self):
        """
        Bibliographic Legends
        v043
        """
        return self.get_field_content("v043", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def bibliographic_strip(self):
        """
        Bibliographic strip
        v043 {'t': 'short_title', 'v': 'volume', 'n': 'number', 's': 'suppl', 'l': 'language', 'c': 'city', 'a': 'year', 'm': 'months'}
        """
        return self.get_field_content(
            "v043",
            subfields={
                "t": "short_title",
                "v": "volume",
                "n": "number",
                "s": "suppl",
                "l": "language",
                "c": "city",
                "a": "year",
                "m": "months",
            },
            single=False,
            simple=False,
        )

    # generated by ModelBuilder
    @cached_property
    def sections(self):
        """
        Sections
        v049
        """
        return self.get_field_content(
            "v049",
            subfields={"l": "language", "t": "text", "c": "code"},
            single=False,
            simple=False,
        )

    # generated by ModelBuilder
    @cached_property
    def publication_date(self):
        """
        Publication Date
        v065
        """
        return self.get_field_content("v065", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def controlled_vocabulary(self):
        """
        Controlled Vocabulary
        v085
        """
        return self.get_field_content("v085", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def processing_date(self):
        """
        Processing Date
        v091
        """
        return self.get_field_content("v091", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def update_date(self):
        """
        Update Date
        v091
        """
        return self.get_field_content("v091", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def creation_date(self):
        """
        Creation Date
        v093
        """
        return self.get_field_content("v093", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def editorial_standard(self):
        """
        Editorial Standard
        v117
        """
        return self.get_field_content("v117", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def total_documents(self):
        """
        Total Documents
        v122
        """
        return self.get_field_content("v122", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def supplement_volume(self):
        """
        Supplement Volume
        v131
        """
        return self.get_field_content("v131", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def supplement_number(self):
        """
        Supplement Number
        v132
        """
        return self.get_field_content("v132", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def is_marked_up(self):
        """
        Is Marked Up
        v200
        """
        return self.get_field_content("v200", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def permissions(self):
        return self.license_code

    @cached_property
    def license_code(self):
        """
        Permissions
        v541
        """
        return self.get_field_content("v541", subfields={}, single=True, simple=True)

    @cached_property
    def license_texts(self):
        """
        Permissions
        v540 {'t': 'html', 'l': 'language'}
        !v540!^t<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a> Todo el contenido de esta revista, excepto d�nde est� identificado, est&#225; bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Licencia Creative Commons</a>^les
        !v540!^t<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a> Todo o conte�do deste peri�dico, exceto onde est&#225 identificado, est&#225; licenciado sob uma <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Licen&#231;a Creative Commons</a>^lpt
        !v540!^t<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a> All the contents of this journal, except where otherwise noted, is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons Attribution License</a>^len
        !v541!BY-NC
        """
        return self.get_field_content(
            "v540",
            subfields={"t": "html", "l": "language"},
            single=False,
            simple=False,
        )

    # generated by ModelBuilder
    @cached_property
    def scielo_domain(self):
        """
        Scielo Domain
        v690
        """
        return self.get_field_content("v690", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def publisher_id(self):
        """
        Publisher Id
        v880
        """
        return self.get_field_content("v880", subfields={}, single=True, simple=True)

    # generated by ModelBuilder
    @cached_property
    def collection_acronym(self):
        """
        Collection Acronym
        v992
        """
        return self.get_field_content("v992", subfields={}, single=True, simple=True)
