# generated by build
from functools import lru_cache

from scielo_classic_website.isisdb.base_c_record import BaseReferenceRecord


# generated by build
class ReferenceRecord(BaseReferenceRecord):
    def __init__(self, record):
        super().__init__(record)

    @property
    @lru_cache(maxsize=1)
    def publication_date(self):
        return self.publication_date_iso

    @property
    @lru_cache(maxsize=1)
    def number(self):
        try:
            return self.issue["number"]
        except (KeyError, TypeError, ValueError):
            return None

    @property
    @lru_cache(maxsize=1)
    def supplement(self):
        try:
            return self.issue["suppl"]
        except (KeyError, TypeError, ValueError):
            return None

    @property
    @lru_cache(maxsize=1)
    def elocation(self):
        try:
            return self.pages_range["elocation"]
        except (KeyError, TypeError, ValueError):
            try:
                return self.pages["elocation"]
            except (KeyError, TypeError, ValueError):
                return None

    @property
    @lru_cache(maxsize=1)
    def page_range(self):
        try:
            return self.pages_range["range"]
        except (KeyError, TypeError, ValueError):
            try:
                return self.pages["range"]
            except (KeyError, TypeError, ValueError):
                return None

    @property
    @lru_cache(maxsize=1)
    def start_page(self):
        try:
            return self.pages["first"]
        except (KeyError, TypeError, ValueError):
            return None

    @property
    @lru_cache(maxsize=1)
    def end_page(self):
        try:
            return self.pages["last"]
        except (KeyError, TypeError, ValueError):
            return None

    @property
    @lru_cache(maxsize=1)
    def publication_type(self):
        """
        This method retrieves the publication type of the citation.
        """
        if super().publication_type:
            return super().publication_type

        if self.patent:
            return "patent"

        if self.conferences:
            return "confproc"

        if self.thesis_degree:
            return "thesis"

        if self.monographic_title:
            return "book"

        if self.article_title:
            return "journal"

        if self.ext_link:
            return "webpage"