# generated by build
from scielo_classic_website.isisdb.base_c_record import BaseReferenceRecord


# generated by build
class ReferenceRecord(BaseReferenceRecord):
    def __init__(self, record):
        super().__init__(record)
