# generated by ModelBuilder
from scielo_classic_website.isisdb.base_h_record import BaseArticleRecord


# generated by ModelBuilder
class ArticleRecord(BaseArticleRecord):

    def __init__(
            self, record, multi_val_tags=None,
            data_dictionary=None):
        super().__init__(
            record, multi_val_tags, data_dictionary)