# generated by ModelBuilder
from scielo_classic_website.isisdb.base_h_record import BaseArticleRecord


# generated by ModelBuilder
class ArticleRecord(BaseArticleRecord):

    def __init__(
            self, record, multi_val_tags=None,
            data_dictionary=None):
        super().__init__(
            record, multi_val_tags, data_dictionary)

    @property
    def scielo_pid_v1(self):
        """
        SciELO PID v1
        v002
        """
        value = self.get_field_content("v002", subfields={}, single=True, simple=True)
        if value and len(value) == 23:
            return value
