# generated by ModelBuilder
from scielo_classic_website.isisdb.base_issue_record import BaseIssueRecord


# generated by ModelBuilder
class IssueRecord(BaseIssueRecord):
    def __init__(self, record, multi_val_tags=None, data_dictionary=None):
        super().__init__(record, multi_val_tags, data_dictionary)

    @property
    def bibliographic_strip_months(self):
        for item in self.bibliographic_strip:
            yield {"lang": item["language"], "text": item.get("months")}

    @property
    def start_month_text(self):
        for item in self.bibliographic_strip_months:
            return (item.get("text") or "").split("/")[0]

    @property
    def end_month_text(self):
        for item in self.bibliographic_strip_months:
            return (item.get("text") or "").split("/")[-1]

    @property
    def start_month(self):
        # FIXME
        return self.start_month_text

    @property
    def end_month(self):
        # FIXME
        return self.end_month_text
