# generated by ModelBuilder
from scielo_migration.isisdb.base_issue_record import BaseIssueRecord


# generated by ModelBuilder
class IssueRecord(BaseIssueRecord):

    def __init__(
            self, record, multi_val_tags=None,
            data_dictionary=None):
        super().__init__(
            record, multi_val_tags, data_dictionary)

    @property
    def start_month_text(self):
        return (self.bibliographic_strip.get("month") or '').split("/")[0]

    @property
    def end_month_text(self):
        return (self.bibliographic_strip.get("month") or '').split("/")[-1]

    @property
    def start_month(self):
        # FIXME
        return self.start_month_text

    @property
    def end_month(self):
        # FIXME
        return self.end_month_text
