# generated by ModelBuilder
from scielo_classic_website.isisdb.base_p_record import BaseParagraphRecord


# generated by ModelBuilder
class ParagraphRecord(BaseParagraphRecord):

    def __init__(
            self, record, multi_val_tags=None,
            data_dictionary=None):
        super().__init__(
            record, multi_val_tags, data_dictionary)