# generated by ModelBuilder
from scielo_migration.isisdb.base_journal_record import BaseJournalRecord


# generated by ModelBuilder
class JournalRecord(BaseJournalRecord):

    def __init__(
            self, record, multi_val_tags=None,
            data_dictionary=None):
        super().__init__(
            record, multi_val_tags, data_dictionary)